
site_name: My IPv6 Journey
site_author: Michael Hubbard (rikosintie)
nav:
  - home: README.md
  - Intro: Introduction.md

theme:
  name: material
  logo: img/ubuntu_icon1.png
  font:
    code: Red Hat Mono
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate # (1)!
  language: en
  favicon: img/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  icon:
    admonition:
      info: octicons/info-16
      note: octicons/tag-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
      success: octicons/check-16
      question: octicons/question-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
    - social
    - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rikosintie
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rikosintie
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mwhubbard/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

copyright: |
  &copy; 2024 <a href="https://github.com/rikosintie" target="_blank" rel="noopener">Michael Hubbard</a>
